### ISSUE TITLE
Real-time Workload Pattern Analysis for Large-scale Cloud Databases has been accepted by PVLDB23

### ISSUE THREAD

**Issue by earthwuyang** [LumingSun/ML4DB-paper-list#11]
I'm greatly thankful for your summarizing papers on AI4DB. I notice the paper _Real-time Workload Pattern Analysis for Large-scale Cloud Databases_ has been accepted by PVLDB23 as shown on  https://dl.acm.org/doi/10.14778/3611540.3611557

**Comment by LumingSun** [comment]
Thanks for the info!
