### ISSUE TITLE
Amending paper list

### ISSUE THREAD

**Issue by Chrosea** [LumingSun/ML4DB-paper-list#9]
In the index structure section, https://github.com/LumingSun/ML4DB-paper-list#index-structure
Looks like "Efficiently Learning Spatial Indices (ICDE 2023)" should be "Efficiently Learning Spatial Indices (VLDB 2020)"

**Comment by LumingSun** [comment]
@Chrosea Thanks for your feedback, it seems these are two different papers from almost the same authors.

Effectively Learning Spatial Indices (VLDB 2020) http://www.vldb.org/pvldb/vol13/p2341-qi.pdf
Efficiently Learning Spatial Indices (ICDE 2023) https://people.eng.unimelb.edu.au/jianzhongq/papers/ICDE2023_ELSI.pdf

**Comment by Chrosea** [comment]
Ahh, thanks for that
